/**
 * SANCTUARY CONFIGURATION
 *
 * Step 1: Open setup.html in your browser to generate your password hash
 * Step 2: Paste the hash below, replacing REPLACE_WITH_YOUR_PASSWORD_HASH
 * Step 3: Customize the fields below as you like
 */
const CONFIG = {

    // SHA-256 hash of your password — generated by setup.html
    passwordHash: '8c2e2d19417b7be32706107e00efe8734cb2acd8e6f2a9a41cc36ae2cffda7ad',

    // The name shown in the browser tab and header
    siteTitle: 'Our Sanctuary',

    // Message shown after login on the vault page
    welcomeMessage: 'Everything we keep, just for us.',

    // Path to your background image (place your photo in the assets/ folder)
    // Leave empty ('') for a solid-color background.
    // Example: 'assets/background.jpg'  or  'assets/our-photo.png'
    backgroundImage: '',

};
